# Generated by Django 4.2 on 2023-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_users_isstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='isStudent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
