# Generated by Django 4.2 on 2023-06-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0002_serviceapplication_projecttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='appType',
            field=models.CharField(max_length=100),
        ),
    ]
