# Generated by Django 4.2 on 2023-06-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('servicesapp', '0003_alter_serviceapplication_apptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='analysisReport',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='equipmentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='equipments.equipment'),
        ),
    ]
