# Generated by Django 4.2 on 2023-06-17 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('appId', models.AutoField(primary_key=True, serialize=False)),
                ('appType', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('svName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('isApproved', models.IntegerField(blank=True, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('equipmentName', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('useDate', models.DateTimeField()),
                ('sampleNum', models.IntegerField()),
                ('sampleType', models.CharField(max_length=100)),
                ('equipmentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
                ('staffInCharged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
