# Generated by Django 4.2 on 2023-05-29 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('appId', models.AutoField(primary_key=True, serialize=False)),
                ('appType', models.CharField(max_length=50)),
                ('svName', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('isApproved', models.BooleanField(blank=True, null=True)),
                ('charges', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicesapp.application')),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
            ],
            bases=('servicesapp.application',),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicesapp.application')),
                ('duration', models.DurationField()),
                ('rentDate', models.DateTimeField()),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
            ],
            bases=('servicesapp.application',),
        ),
    ]
