# Generated by Django 4.2 on 2023-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rentDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
