# Generated by Django 4.2 on 2023-05-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0002_alter_rental_rentdate_alter_sample_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rentDate',
            field=models.DateTimeField(),
        ),
    ]
