# Generated by Django 4.2 on 2023-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0002_alter_application_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='equipmentName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='isApproved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
