# Generated by Django 4.2 on 2023-06-29 07:32

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0004_serviceapplication_analysisreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='analysisReport',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to=''),
        ),
    ]
