# Generated by Django 4.2 on 2023-06-30 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0001_initial'),
        ('servicesapp', '0005_alter_serviceapplication_analysisreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='equipmentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipments.equipment'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='staffInCharged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
