# Generated by Django 4.2 on 2023-06-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesapp', '0006_alter_serviceapplication_equipmentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceapplication',
            name='charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
